### ISSUE TITLE
Setup build pipeline with AppVeyor

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.Targets.MauiLog#1]
AppVeyor-file is ready, so just need the last push

NLog.Targets.Xamarin is now replaced by NLog.Targets.MauiLog, since Xamarin will reach end-of-life at May 1, 2024

**Comment by 304NotModified** [comment]
working on this

**Comment by 304NotModified** [comment]
Done and checked. Badge in readme is also working.

**Comment by snakefoot** [comment]
Thank you very much. Very happy with the release of the nuget-package:

- https://www.nuget.org/packages/NLog.Targets.MauiLog
