### ISSUE TITLE
Missing Preserve Attribute for AppleOSLogTarget

### ISSUE THREAD

**Issue by bfmyr4** [NLog/NLog.Targets.MauiLog#10]
Xamarin.iOS will not load the MauiLog Target unless the following is added somewhere in the iOS portion of the solution.
[assembly: Preserve(typeof(NLog.Targets.AppleOSLogTarget), AllMembers = true)]

This should either be put in AppleOSLogTarget directly or should be noted in the readme.

**Comment by snakefoot** [comment]
Thought that `ILLink.Descriptors.xml` would do the trick:

https://github.com/NLog/NLog.Targets.MauiLog/blob/d21d68da21919d735ab408bfb48a2c71219b6e7c/src/NLog.Targets.MauiLog/NLog.Targets.MauiLog.csproj#L36

But maybe one need to apply:

`<TrimmerRootDescriptor Include="ILLink.Descriptors.xml" />`

Pull-requests are most wellcome.

**Comment by bfmyr4** [comment]
This appears to only be an issue on Xamarin, Maui works fine.

**Comment by snakefoot** [comment]
Thought that Xamarin would listen to the [PreserveAttribute.cs](https://github.com/NLog/NLog.Targets.MauiLog/blob/master/src/NLog.Targets.MauiLog/Internal/PreserveAttribute.cs)

https://github.com/NLog/NLog.Targets.MauiLog/blob/d21d68da21919d735ab408bfb48a2c71219b6e7c/src/NLog.Targets.MauiLog/Properties/AssemblyInfo.cs#L4

**Comment by snakefoot** [comment]
But maybe missing the `, AllMembers = true)]`

**Comment by bfmyr4** [comment]
I use that attribute in my Xamarin Solution, but include the type in the constructor:

**Comment by snakefoot** [comment]
Thought one could specify it should be for all types in the assembly
