### ISSUE TITLE
Update nuget-owner for NLog.Targets.MauiLog

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.Targets.MauiLog#20]
Possible to update the owner to include `NLogLogging` for the nuget-package:

https://www.nuget.org/packages/NLog.Targets.MauiLog

![image](https://github.com/NLog/NLog.Targets.MauiLog/assets/11509660/bd8a879d-e92d-42d3-98da-5bb4fd8bb106)

**Comment by 304NotModified** [comment]
@snakefoot done!

**Comment by snakefoot** [comment]
Excellent. Thank you so much.
