### ISSUE TITLE
Path for retrieving the log

### ISSUE THREAD

**Issue by luiey-coretekno** [NLog/NLog.Targets.MauiLog#23]
Where do I get the log file from android phone? Does it need to config to specific path to get the log file? Or does it just log to the output only?

**Comment by snakefoot** [comment]
This MauiLog-target outputs to the following destinations:
- Apple iOS / MacOS - Unified Logging OSLog (replacement of print and NSLog)
- Android - Android.Util.Log / LogCat
- NetStandard - System.Diagnostics.Debugger.Log

I was thinking that one would use the native LogViewer on the actual device.

- Android would use [LogCat](https://developer.android.com/studio/debug/am-logcat)
- iOS would use [OSLog Viewer](https://medium.com/@ajvanderlee/oslog-and-unified-logging-as-recommended-by-apple-47fad0d73282)
- Debugging in Visual Studio would use the output-window

If you use the NLog FileTarget then you can consider using [${specialfolder}](https://github.com/NLog/NLog/wiki/Special-Folder-Layout-Renderer) in the [FileName](https://github.com/NLog/NLog/wiki/File-target#filename-directory)-option.

**Comment by snakefoot** [comment]
Closing question as answered, due to inactivity.

**Comment by bronteq** [comment]
Hi @snakefoot , Gdc layout renderer works perfectly with Maui File system helpers, thanks!
