### ISSUE TITLE
working example

### ISSUE THREAD

**Issue by vovanb** [NLog/NLog.Targets.MauiLog#5]
Hi
can you provide working example how to use that library with MAUI application. How to access logs?
Exist similar project https://github.com/jfversluis/MauiMetroLogSample but it another library. I would prefer to use Nlog

**Comment by snakefoot** [comment]
I was thinking that one would use the native LogViewer on the actual device.
- Android would use LogCat
- iOS would use [OSLog Viewer](https://medium.com/@ajvanderlee/oslog-and-unified-logging-as-recommended-by-apple-47fad0d73282)

**Comment by vovanb** [comment]
Thanks for reply, but I am looking for example how to use NLog.Targets.MauiLog with MAUI project. Do you have such basic guidance or sample project?

**Comment by snakefoot** [comment]
You just add the nuget-package to your project, and include the MauiLog-target in your NLog.config - file (As shown on the "front page" of this repository)



Sent from my Galaxy



-------- Original message --------
From: vovanb ***@***.***>
Date: 18/11/2022 09:26 (GMT+01:00)
To: "NLog/NLog.Targets.MauiLog" ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog.Targets.MauiLog] working example (Issue #5)


Thanks for reply, but I am looking for example how to use NLog.Targets.MauiLog with MAUI project. Do you have such basic guidance or sample project?

**Comment by SF-Simon** [comment]
Yes, if you have familiar usage and examples, I would appreciate it if you could share some basic usage and advanced skills.
It's better to help improve the ReadMe.md. People like me who have just met are in great need.

thank you

**Comment by ReneSorensenBaader** [comment]
I agree please provide a sample that shows how to use this.

**Comment by snakefoot** [comment]
Created #13 with MAUI-Sample-Applications where NLog is setup as LoggingProvider.

Updated the docs - https://github.com/snakefoot/NLog.Targets.MauiLog/blob/master/README.md

Will be merged when NLog v5.2 has been released, that improves support for application trimming:

Preview: https://github.com/snakefoot/NLog.github.io/blob/master/_posts/2023-05-16-nlog-5-2-trim-warnings.md

**Comment by snakefoot** [comment]
NLog.Targets.MauiLog v5.2.0 has been released https://www.nuget.org/packages/NLog.Targets.MauiLog/5.2.0

Example MAUI application can be found here: https://github.com/NLog/NLog.Targets.MauiLog/tree/master/examples/MauiApp2

Have tried to improve the tutorial in README.md here: https://github.com/NLog/NLog.Targets.MauiLog/blob/master/README.md
