### ISSUE TITLE
Invalid target in nlog config

### ISSUE THREAD

**Issue by erdmenchen** [NLog/NLog.Targets.MauiLog#8]
When following the instructions in the Readme, the target is not recognized by the xsd schema:

![image](https://user-images.githubusercontent.com/6791096/214554980-f32bf79a-c219-4e7f-a771-97a3000a0cfd.png)

What am I missing?

using 
Nlog 5.1.1
Nlog.Targets.MauiLog 1.0.2

**Comment by snakefoot** [comment]
Thank you for the feedback. Have created #9 to replace `xsi:type` with `type` to avoid xml-schema-validation-errors (Since `MauiLog` is not included in XML-schema).

**Comment by erdmenchen** [comment]
Thank you for your fast response!
Unfortunately then the whole entry becomes invalid, so I would not consider this issue as fixed...

Basically I can't get NLog to work with .NET MAUI at all...
Is there an example project where NLog was successfully integrated by you?

**Comment by snakefoot** [comment]
> Unfortunately then the whole entry becomes invalid

Can you give a screenshot of the error-message you get, when replacing `xsi:type` with `type` ?

> Basically I can't get NLog to work with .NET MAUI at all...

Have you checked the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) output? Have you checked that the NLog.config is actually deployed (`copy if newer`) with the application?

> Is there an example project where NLog was successfully integrated by you?

MAUI is pretty much all known platforms. Any platform in particular you are interested in?
